export const dataGridLocaleTextTranslateFull = {
    toolbarDensity: "Densidade",
    toolbarDensityLabel: "Densidade",
    toolbarDensityCompact: "Compacto",
    toolbarDensityStandard: "Padrão",
    toolbarDensityComfortable: "Confortável",
    toolbarColumns: "Colunas",
    toolbarColumnsLabel: "Selecionar colunas",
    toolbarFilters: "Filtros",
    toolbarFiltersLabel: "Mostrar filtros",
    toolbarFiltersTooltipHide: "Esconder filtros",
    toolbarFiltersTooltipShow: "Mostrar filtros",
    toolbarExport: "Exportar",
    toolbarExportLabel: "Exportar",
    toolbarExportCSV: "Baixar CSV",
    toolbarExportPrint: "Imprimir",
    columnHeaderSortIconLabel: "Ordenar",
    columnMenuUnsort: "Remover ordenação",
    columnMenuSortAsc: "Ordenar por ordem crescente",
    columnMenuSortDesc: "Ordenar por ordem decrescente",
    columnMenuFilter: "Filtrar",
    columnMenuHideColumn: "Ocultar coluna",
    columnMenuShowColumns: "Mostrar colunas",
    columnMenuManageColumns: "Gerenciar colunas",
    columnsPanelTextFieldLabel: "Título da coluna",
    columnsPanelHideAllButton: "OCULTAR TODAS",
    columnsPanelShowAllButton: "MOSTRAR TODAS",
    columnsPanelTextFieldPlaceholder: "Título da coluna",
    filterPanelAddFilter: "Adicionar filtro",
    filterPanelDeleteIconLabel: "Remover",
    filterPanelLogicOperator: "Operador lógico",
    filterPanelOperator: "Operador",
    filterPanelInputLabel: "Valor",
    filterPanelInputPlaceholder: "Valor do filtro",
    filterPanelColumns: "Colunas",
    filterOperatorContains: "contém",
    filterOperatorEquals: "é igual a",
    filterOperatorStartsWith: "começa com",
    filterOperatorEndsWith: "termina com",
    filterOperatorIs: "é",
    filterOperatorNot: "não é",
    filterOperatorAfter: "é depois de",
    filterOperatorOnOrAfter: "é em ou depois de",
    filterOperatorBefore: "é antes de",
    filterOperatorOnOrBefore: "é em ou antes de",
    filterOperatorIsEmpty: "está vazio",
    filterOperatorIsNotEmpty: "não está vazio",
    filterOperatorIsAnyOf: "é qualquer um de",
    footerRowSelected: (count: number) =>
        count > 1 ? `${count.toLocaleString()} linhas selecionadas` : `${count.toLocaleString()} linha selecionada`,
    noRowsLabel: "Nenhum registro",
    noResultsOverlayLabel: "Nenhum registro encontrado",
    MuiTablePagination: { labelRowsPerPage: "Linhas por página" },
};

export const getDataGridStyles = (colorBorderSystem: string, colorScrollSystem: string) => ({
    borderColor: colorBorderSystem,
    borderRadius: "16px",
    "& .MuiDataGrid-columnSeparator": {
        color: colorBorderSystem,
    },
    "& .MuiDataGrid-columnHeaders": {
        borderBottom: `1px solid ${colorBorderSystem}`,
    },
    "& .MuiDataGrid-footerContainer": {
        borderTop: `1px solid ${colorBorderSystem}`,
    },
    "& .MuiDataGrid-cell": {
        borderColor: colorBorderSystem,
    },
    "& .MuiDataGrid-virtualScroller": {
        "&::-webkit-scrollbar": {
            width: "6px",
            height: "10px",
        },
        "&::-webkit-scrollbar-thumb": {
            backgroundColor: colorBorderSystem,
            borderRadius: "10px",
        },
        "&::-webkit-scrollbar-thumb:hover": {
            backgroundColor: colorScrollSystem,
        },
    },
});
