export const ArrayTypesSurveyRHPortfolios = [
    { id: "ADMINISTRAÇÃO DE PESSOAL", label: "ADMINISTRAÇÃO DE PESSOAL" },
    { id: "AGRO", label: "AGRO" },
    { id: "ANÁLISE E CONDUÇÃO DE CRÉDITO", label: "ANÁLISE E CONDUÇÃO DE CRÉDITO" },
    { id: "CADASTRO", label: "CADASTRO" },
    { id: "CENTRAL", label: "CENTRAL" },
    { id: "CIDADANIA E SUSTENTABILIDADE", label: "CIDADANIA E SUSTENTABILIDADE" },
    { id: "COMUNICAÇÃO EXTERNA", label: "COMUNICAÇÃO EXTERNA" },
    { id: "CONSOLIDADO", label: "CONSOLIDADO" },
    { id: "CONTÁBIL E TRIBUTÁRIO", label: "CONTÁBIL E TRIBUTÁRIO" },
    { id: "CONTAS A PAGAR", label: "CONTAS A PAGAR" },
    { id: "CONTROLE", label: "CONTROLE" },
    { id: "CONTROLE INTERNO", label: "CONTROLE INTERNO" },
    { id: "CREDITO", label: "CREDITO" },
    { id: "CRÉDITO E INVESTIMENTO", label: "CRÉDITO E INVESTIMENTO" },
    { id: "DESENVOLVIMENTO", label: "DESENVOLVIMENTO" },
    { id: "DIRETORIA", label: "DIRETORIA" },
    { id: "DOCUMENTAÇÃO E ESTOQUE", label: "DOCUMENTAÇÃO E ESTOQUE" },
    { id: "ENDOMARKETING", label: "ENDOMARKETING" },
    { id: "EXPERIÊNCIA", label: "EXPERIÊNCIA" },
    { id: "FIDELIZAÇÃO", label: "FIDELIZAÇÃO" },
    { id: "FINANCEIRO", label: "FINANCEIRO" },
    { id: "GECAD", label: "GECAD" },
    { id: "GEPES", label: "GEPES" },
    { id: "GEPRO", label: "GEPRO" },
    { id: "GESTÃO DE PESSOAL", label: "GESTÃO DE PESSOAL" },
    { id: "GOVERNANCA", label: "GOVERNANCA" },
    { id: "HUNTER", label: "HUNTER" },
    { id: "INOVACAO", label: "INOVACAO" },
    { id: "INOVAÇÃO", label: "INOVAÇÃO" },
    { id: "INTELIGENCIA DE NEGOCIO", label: "INTELIGENCIA DE NEGOCIO" },
    { id: "INTELIGÊNCIA DE NEGÓCIOS", label: "INTELIGÊNCIA DE NEGÓCIOS" },
    { id: "JURIDICO", label: "JURIDICO" },
    { id: "LIMITES DE CRÉDITO", label: "LIMITES DE CRÉDITO" },
    { id: "MARKETING", label: "MARKETING" },
    { id: "MEIOS DE PAGAMENTO", label: "MEIOS DE PAGAMENTO" },
    { id: "OBRAS E PATRIMÔNIO", label: "OBRAS E PATRIMÔNIO" },
    { id: "OQS", label: "OQS" },
    { id: "ORÇAMENTO E CONTRATOS", label: "ORÇAMENTO E CONTRATOS" },
    { id: "PATRIMONIO", label: "PATRIMONIO" },
    { id: "PF ALTO RELACIONAMENTO", label: "PF ALTO RELACIONAMENTO" },
    { id: "PF RELACIONAMENTO", label: "PF RELACIONAMENTO" },
    { id: "PF VAREJO", label: "PF VAREJO" },
    { id: "PJ GRANDES CORPORAÇÕES", label: "PJ GRANDES CORPORAÇÕES" },
    { id: "PJ RELACIONAMENTO", label: "PJ RELACIONAMENTO" },
    { id: "PJ VAREJO", label: "PJ VAREJO" },
    { id: "PLANEJAMENTO E PROTECAO", label: "PLANEJAMENTO E PROTECAO" },
    { id: "PLANEJAMENTO E PROTEÇÃO", label: "PLANEJAMENTO E PROTEÇÃO" },
    { id: "PLATAFORMA PJ", label: "PLATAFORMA PJ" },
    { id: "PLATAFORMA RURAL", label: "PLATAFORMA RURAL" },
    { id: "RECUPERACAO", label: "RECUPERACAO" },
    { id: "RECUPERAÇÃO DE CRÉDITO", label: "RECUPERAÇÃO DE CRÉDITO" },
    { id: "RELACIONAMENTO", label: "RELACIONAMENTO" },
    { id: "SECRETARIA", label: "SECRETARIA" },
    { id: "SUSTENTABILIDADE", label: "SUSTENTABILIDADE" },
    { id: "TESOURARIA E CONTA CORRENTE", label: "TESOURARIA E CONTA CORRENTE" },
    { id: "TI", label: "TI" },
    { id: "VAREJO", label: "VAREJO" },
];
