export const ArrayTypesIncomeTypes = [
    { id: "SALÁRIO", label: "SALÁRIO" },
    { id: "RENDIMENTO NÃO COMPROVADO", label: "RENDIMENTO NÃO COMPROVADO" },
    { id: "RENDA PONDERADA", label: "RENDA PONDERADA" },
    { id: "RECUSOU-SE A INFORMAR RENDA", label: "RECUSOU-SE A INFORMAR RENDA" },
    { id: "RECUSOU-SE A INFORMAR FATURAMENTO", label: "RECUSOU-SE A INFORMAR FATURAMENTO" },
    { id: "PRO-LABORE", label: "PRO-LABORE" },
    { id: "PREVISÃO DE FATURAMENTO", label: "PREVISÃO DE FATURAMENTO" },
    { id: "PRESTAÇÃO DE SERVIÇO", label: "PRESTAÇÃO DE SERVIÇO" },
    { id: "PENSÃO ALIMENTÍCIA", label: "PENSÃO ALIMENTÍCIA" },
    { id: "OUTROS", label: "OUTROS" },
    { id: "NÃO POSSUI RENDA", label: "NÃO POSSUI RENDA" },
    { id: "NÃO POSSUI FATURAMENTO", label: "NÃO POSSUI FATURAMENTO" },
    { id: "NÃO INFORMADO", label: "NÃO INFORMADO" },
    { id: "MESADA", label: "MESADA" },
    { id: "FATURAMENTO", label: "FATURAMENTO" },
    { id: "EXTRATOS DE CONTA CORRENTE", label: "EXTRATOS DE CONTA CORRENTE" },
    { id: "DECLARAÇÃO DE RENDA", label: "DECLARAÇÃO DE RENDA" },
    { id: "DECLARAÇÃO DE FATURAMENTO", label: "DECLARAÇÃO DE FATURAMENTO" },
    { id: "CONSULTORIA", label: "CONSULTORIA" },
    { id: "BUREAU EXTERNO", label: "BUREAU EXTERNO" },
    { id: "APOSENTADORIA", label: "APOSENTADORIA" },
    { id: "APLICAÇÃO", label: "APLICAÇÃO" },
    { id: "AGROPECUÁRIA", label: "AGROPECUÁRIA" },
];
